### ISSUE TITLE
No avalaible session found in the latest update

### ISSUE THREAD

**Issue by xMonologue** [Nahelam/t5sp-session-fix#3]
Hello! I tested the latest release and it seems a stealth plutonium update broke the plugin again. For my servers cannot be joined after a bit with the error "no avalaible session found" it seems the plugin does not do anything anymore. Does this plan to be fixed? I did notice most other servers have the same issue.

**Comment by xMonologue** [comment]
[SESSION FIX] Failed to recreate session
Plutonium r3755 > 
[SESSION FIX] Something went wrong with dwCreateSession
Plutonium r3755 > 
[SESSION FIX] Will try to recreate session again soon...

Thats the error I get and the servers won't start.

**Comment by xMonologue** [comment]
Plutonium r3755 > 
[SESSION FIX] Something went wrong with dwCreateSession

Plutonium r3755 > 
[SESSION FIX] Reached session create failures limit, will attempt a whole reconnect...

**Comment by Nahelam** [comment]
Hi, does it still happen? I asked around and the plugin seems to be stable.

**Comment by Lemon0900** [comment]
> Hi, does it still happen? I asked around and the plugin seems to be stable.

sometimes i still get the error

**Comment by Nahelam** [comment]
Unfortunately I don't know why it fails sometimes, and I don't have time to investigate further. It seems to be pretty rare though. Let's hope that this session thing will be fixed by the Plutonium team someday.
